INSERT INTO track (trackname) VALUES
('Data Science'),
('Machine Learning'),
('Artificial Intelligence'),
('Web Development'),
('Mobile App Development'),
('Cloud Computing'),
('Cybersecurity'),
('Data Engineering'),
('DevOps'),
('Software Testing'),
('UI/UX Design'),
('Blockchain Development'),
('Game Development'),
('Embedded Systems'),
('Internet of Things'),
('Business Intelligence'),
('Database Administration'),
('Network Engineering'),
('Robotics Engineering'),
('Data Analytics');
