INSERT INTO question (CourseID, QuestionText, QuestionType, DifficultyLevel, Marks) VALUES
(1, 'What is Power BI primarily used for?', 'MCQ', 1, 1),
(1, 'True or False: Power BI is a Microsoft product.', 'TF', 1, 1),
(1, 'Which component is used to create reports in Power BI?', 'MCQ', 2, 2),
(1, 'What type of data sources can Power BI connect to?', 'MCQ', 2, 2),
(1, 'True or False: Power BI Desktop is web-based only.', 'TF', 1, 1),
(1, 'What is a DAX formula used for in Power BI?', 'MCQ', 3, 3),
(1, 'Which visualization shows trends over time most effectively?', 'MCQ', 2, 2),
(1, 'True or False: Power BI can connect to Excel files.', 'TF', 1, 1),
(1, 'What is the purpose of Power Query in Power BI?', 'MCQ', 3, 3),
(1, 'True or False: Dashboards and reports are the same in Power BI.', 'TF', 2, 2),
(2, 'What is the output of print(2 + 2)?', 'MCQ', 1, 1),
(2, 'True or False: Python is a compiled language.', 'TF', 2, 2),
(2, 'Which keyword is used to define a function in Python?', 'MCQ', 1, 1),
(2, 'What is the correct file extension for Python files?', 'MCQ', 1, 1),
(2, 'True or False: Python uses indentation to define code blocks.', 'TF', 1, 1),
(2, 'Which data type is used to store True or False values?', 'MCQ', 1, 1),
(2, 'What does the len() function return?', 'MCQ', 2, 2),
(2, 'True or False: Lists in Python are mutable.', 'TF', 2, 2),
(2, 'Which operator is used for exponentiation in Python?', 'MCQ', 2, 2),
(2, 'True or False: Python supports multiple inheritance.', 'TF', 3, 3),
(3, 'What keyword is used to create a variable in Python?', 'MCQ', 1, 1),
(3, 'True or False: Python requires semicolons at the end of statements.', 'TF', 1, 1),
(3, 'Which loop is used to iterate over a sequence?', 'MCQ', 2, 2),
(3, 'What is the purpose of the break statement?', 'MCQ', 2, 2),
(3, 'True or False: Tuples are immutable in Python.', 'TF', 2, 2),
(3, 'Which method adds an element to the end of a list?', 'MCQ', 2, 2),
(3, 'What is a lambda function in Python?', 'MCQ', 3, 3),
(3, 'True or False: Dictionaries store key-value pairs.', 'TF', 2, 2),
(3, 'What does the continue statement do in a loop?', 'MCQ', 2, 2),
(3, 'True or False: Python is case-sensitive.', 'TF', 1, 1),
(4, 'What does SQL stand for?', 'MCQ', 1, 1),
(4, 'True or False: SQL is used to manage relational databases.', 'TF', 1, 1),
(4, 'Which SQL command retrieves data from a database?', 'MCQ', 1, 1),
(4, 'What clause is used to filter records in SQL?', 'MCQ', 2, 2),
(4, 'True or False: DELETE removes all records from a table.', 'TF', 2, 2),
(4, 'Which keyword is used to sort query results?', 'MCQ', 2, 2),
(4, 'What does the DISTINCT keyword do?', 'MCQ', 2, 2),
(4, 'True or False: Primary keys can contain NULL values.', 'TF', 2, 2),
(4, 'Which operator is used for pattern matching in SQL?', 'MCQ', 2, 2),
(4, 'True or False: SQL is case-sensitive by default.', 'TF', 2, 2),
(5, 'What is the main purpose of data visualization?', 'MCQ', 1, 1),
(5, 'True or False: Power BI supports custom visuals.', 'TF', 2, 2),
(5, 'Which chart type is best for showing composition?', 'MCQ', 2, 2),
(5, 'What is a KPI visual used for?', 'MCQ', 2, 2),
(5, 'True or False: Slicers can filter multiple visuals.', 'TF', 2, 2),
(5, 'What is drill-down functionality in Power BI?', 'MCQ', 3, 3),
(5, 'Which visual shows geographical data?', 'MCQ', 2, 2),
(5, 'True or False: Conditional formatting can be applied to tables.', 'TF', 2, 2),
(5, 'What are bookmarks used for in Power BI?', 'MCQ', 3, 3),
(5, 'True or False: You can export Power BI visuals to PowerPoint.', 'TF', 2, 2),
(6, 'What is the difference between supervised and unsupervised learning?', 'MCQ', 2, 2),
(6, 'True or False: Machine learning is a subset of AI.', 'TF', 1, 1),
(6, 'What is a training dataset used for?', 'MCQ', 2, 2),
(6, 'Which algorithm is used for classification problems?', 'MCQ', 3, 3),
(6, 'True or False: Overfitting occurs when a model performs poorly on training data.', 'TF', 3, 3),
(6, 'What is the purpose of cross-validation?', 'MCQ', 3, 3),
(6, 'Which metric measures classification accuracy?', 'MCQ', 2, 2),
(6, 'True or False: Feature engineering improves model performance.', 'TF', 2, 2),
(6, 'What is a regression problem in machine learning?', 'MCQ', 2, 2),
(6, 'True or False: K-means is a supervised learning algorithm.', 'TF', 3, 3),
(7, 'What is TensorFlow primarily used for?', 'MCQ', 2, 2),
(7, 'True or False: Neural networks are inspired by the human brain.', 'TF', 1, 1),
(7, 'What is a tensor in TensorFlow?', 'MCQ', 3, 3),
(7, 'Which activation function is commonly used in hidden layers?', 'MCQ', 3, 3),
(7, 'True or False: Backpropagation is used to update weights.', 'TF', 3, 3),
(7, 'What is the purpose of a convolutional layer?', 'MCQ', 4, 4),
(7, 'Which optimizer is commonly used in deep learning?', 'MCQ', 3, 3),
(7, 'True or False: Dropout is a regularization technique.', 'TF', 3, 3),
(7, 'What is an epoch in neural network training?', 'MCQ', 2, 2),
(7, 'True or False: GPU acceleration speeds up deep learning training.', 'TF', 2, 2),
(8, 'What is Pandas primarily used for in Python?', 'MCQ', 1, 1),
(8, 'True or False: DataFrame is a Pandas data structure.', 'TF', 1, 1),
(8, 'Which method reads a CSV file into a DataFrame?', 'MCQ', 2, 2),
(8, 'What does the head() method do?', 'MCQ', 1, 1),
(8, 'True or False: Series is a one-dimensional labeled array.', 'TF', 2, 2),
(8, 'Which method is used to group data in Pandas?', 'MCQ', 2, 2),
(8, 'What does the fillna() method do?', 'MCQ', 2, 2),
(8, 'True or False: merge() combines DataFrames horizontally.', 'TF', 3, 3),
(8, 'Which method removes duplicate rows?', 'MCQ', 2, 2),
(8, 'True or False: Pandas can handle time series data.', 'TF', 2, 2),
(9, 'What is the mean of a dataset?', 'MCQ', 1, 1),
(9, 'True or False: Standard deviation measures data spread.', 'TF', 2, 2),
(9, 'What is the purpose of hypothesis testing?', 'MCQ', 3, 3),
(9, 'Which distribution is bell-shaped and symmetric?', 'MCQ', 2, 2),
(9, 'True or False: Correlation implies causation.', 'TF', 2, 2),
(9, 'What is a p-value used for in statistics?', 'MCQ', 3, 3),
(9, 'Which measure is resistant to outliers?', 'MCQ', 2, 2),
(9, 'True or False: Variance is the square of standard deviation.', 'TF', 2, 2),
(9, 'What is a confidence interval?', 'MCQ', 3, 3),
(9, 'True or False: A larger sample size increases statistical power.', 'TF', 3, 3),
(10, 'What is data cleaning?', 'MCQ', 1, 1),
(10, 'True or False: Missing values should always be removed.', 'TF', 2, 2),
(10, 'Which technique handles missing numerical data?', 'MCQ', 2, 2),
(10, 'What are outliers in a dataset?', 'MCQ', 2, 2),
(10, 'True or False: Data normalization scales values to a common range.', 'TF', 2, 2),
(10, 'What is the purpose of data validation?', 'MCQ', 2, 2),
(10, 'Which method detects duplicate records?', 'MCQ', 2, 2),
(10, 'True or False: Data profiling helps understand data quality.', 'TF', 2, 2),
(10, 'What is ETL in data preparation?', 'MCQ', 3, 3),
(10, 'True or False: Feature scaling improves model convergence.', 'TF', 3, 3),
(11, 'What does HTML stand for?', 'MCQ', 1, 1),
(11, 'True or False: HTML is a programming language.', 'TF', 1, 1),
(11, 'Which tag creates a hyperlink in HTML?', 'MCQ', 1, 1),
(11, 'What is the purpose of the <head> tag?', 'MCQ', 2, 2),
(11, 'True or False: CSS is used for styling web pages.', 'TF', 1, 1),
(11, 'Which HTML tag creates a paragraph?', 'MCQ', 1, 1),
(11, 'What does CSS stand for?', 'MCQ', 1, 1),
(11, 'True or False: Inline styles override external CSS.', 'TF', 2, 2),
(11, 'Which property changes text color in CSS?', 'MCQ', 1, 1),
(11, 'True or False: The <div> tag is a block-level element.', 'TF', 2, 2),
(12, 'What is JavaScript primarily used for?', 'MCQ', 1, 1),
(12, 'True or False: JavaScript and Java are the same language.', 'TF', 1, 1),
(12, 'Which keyword declares a constant in JavaScript?', 'MCQ', 2, 2),
(12, 'What is the output of typeof null in JavaScript?', 'MCQ', 3, 3),
(12, 'True or False: JavaScript is single-threaded.', 'TF', 2, 2),
(12, 'Which method adds an element to an array?', 'MCQ', 2, 2),
(12, 'What is a callback function?', 'MCQ', 3, 3),
(12, 'True or False: Arrow functions have their own this context.', 'TF', 3, 3),
(12, 'What does JSON stand for?', 'MCQ', 2, 2),
(12, 'True or False: let and var have the same scope.', 'TF', 2, 2),
(13, 'What is React used for?', 'MCQ', 1, 1),
(13, 'True or False: React is a JavaScript library.', 'TF', 1, 1),
(13, 'What is a component in React?', 'MCQ', 2, 2),
(13, 'Which method is used to update state in class components?', 'MCQ', 2, 2),
(13, 'True or False: Hooks can only be used in class components.', 'TF', 2, 2),
(13, 'What is the purpose of useState hook?', 'MCQ', 2, 2),
(13, 'Which method renders a React component to the DOM?', 'MCQ', 2, 2),
(13, 'True or False: JSX is valid JavaScript syntax.', 'TF', 2, 2),
(13, 'What is the Virtual DOM in React?', 'MCQ', 3, 3),
(13, 'True or False: Props are mutable in React.', 'TF', 2, 2),
(14, 'What is Node.js?', 'MCQ', 1, 1),
(14, 'True or False: Node.js runs JavaScript on the server.', 'TF', 1, 1),
(14, 'Which module is used to create a server in Node.js?', 'MCQ', 2, 2),
(14, 'What is npm used for?', 'MCQ', 2, 2),
(14, 'True or False: Express.js is a Node.js framework.', 'TF', 2, 2),
(14, 'What is middleware in Express?', 'MCQ', 3, 3),
(14, 'Which method handles GET requests in Express?', 'MCQ', 2, 2),
(14, 'True or False: Node.js is single-threaded.', 'TF', 2, 2),
(14, 'What is the purpose of package.json?', 'MCQ', 2, 2),
(14, 'True or False: Async/await simplifies asynchronous code.', 'TF', 3, 3),
(15, 'What is database normalization?', 'MCQ', 2, 2),
(15, 'True or False: A primary key uniquely identifies a record.', 'TF', 1, 1),
(15, 'What is a foreign key used for?', 'MCQ', 2, 2),
(15, 'Which normal form eliminates partial dependencies?', 'MCQ', 3, 3),
(15, 'True or False: Denormalization improves query performance.', 'TF', 3, 3),
(15, 'What is an entity in database design?', 'MCQ', 2, 2),
(15, 'Which relationship type connects two entities?', 'MCQ', 2, 2),
(15, 'True or False: Composite keys consist of multiple columns.', 'TF', 2, 2),
(15, 'What is a schema in database design?', 'MCQ', 2, 2),
(15, 'True or False: Indexes speed up data retrieval.', 'TF', 2, 2),
(16, 'What is a subquery in SQL?', 'MCQ', 3, 3),
(16, 'True or False: Joins combine rows from multiple tables.', 'TF', 2, 2),
(16, 'Which join returns all rows from both tables?', 'MCQ', 3, 3),
(16, 'What does GROUP BY do in SQL?', 'MCQ', 2, 2),
(16, 'True or False: HAVING filters groups in SQL.', 'TF', 3, 3),
(16, 'What is the purpose of a CTE in SQL?', 'MCQ', 4, 4),
(16, 'Which aggregate function counts rows?', 'MCQ', 2, 2),
(16, 'True or False: UNION removes duplicate rows.', 'TF', 3, 3),
(16, 'What is a window function in SQL?', 'MCQ', 4, 4),
(16, 'True or False: CASE statements provide conditional logic.', 'TF', 2, 2),
(17, 'What does NoSQL stand for?', 'MCQ', 1, 1),
(17, 'True or False: MongoDB is a document-oriented database.', 'TF', 1, 1),
(17, 'Which data format does MongoDB use?', 'MCQ', 2, 2),
(17, 'What is a collection in MongoDB?', 'MCQ', 2, 2),
(17, 'True or False: NoSQL databases require fixed schemas.', 'TF', 2, 2),
(17, 'Which method inserts a document in MongoDB?', 'MCQ', 2, 2),
(17, 'What is sharding in MongoDB?', 'MCQ', 4, 4),
(17, 'True or False: MongoDB supports ACID transactions.', 'TF', 3, 3),
(17, 'What is replication in MongoDB?', 'MCQ', 3, 3),
(17, 'True or False: MongoDB queries use SQL syntax.', 'TF', 2, 2),
(18, 'What is Flask in Python?', 'MCQ', 1, 1),
(18, 'True or False: Flask is a microframework.', 'TF', 1, 1),
(18, 'Which decorator defines a route in Flask?', 'MCQ', 2, 2),
(18, 'What is the purpose of render_template()?', 'MCQ', 2, 2),
(18, 'True or False: Flask includes an ORM by default.', 'TF', 2, 2),
(18, 'Which method handles POST requests in Flask?', 'MCQ', 2, 2),
(18, 'What is Jinja2 used for in Flask?', 'MCQ', 2, 2),
(18, 'True or False: Flask supports blueprints for modular apps.', 'TF', 3, 3),
(18, 'What is the purpose of request.form?', 'MCQ', 2, 2),
(18, 'True or False: Flask runs on the development server by default.', 'TF', 2, 2),
(19, 'What is Django?', 'MCQ', 1, 1),
(19, 'True or False: Django follows the MVT pattern.', 'TF', 2, 2),
(19, 'What is the Django ORM used for?', 'MCQ', 2, 2),
(19, 'Which command creates a new Django project?', 'MCQ', 2, 2),
(19, 'True or False: Django includes user authentication by default.', 'TF', 2, 2),
(19, 'What is a Django app?', 'MCQ', 2, 2),
(19, 'Which file contains URL patterns in Django?', 'MCQ', 2, 2),
(19, 'True or False: Django templates use Python syntax.', 'TF', 2, 2),
(19, 'What is migrations in Django?', 'MCQ', 3, 3),
(19, 'True or False: Django admin is auto-generated.', 'TF', 2, 2),
(20, 'What is Git used for?', 'MCQ', 1, 1),
(20, 'True or False: Git is a version control system.', 'TF', 1, 1),
(20, 'Which command initializes a Git repository?', 'MCQ', 1, 1),
(20, 'What does git commit do?', 'MCQ', 2, 2),
(20, 'True or False: Branches allow parallel development.', 'TF', 2, 2),
(20, 'Which command merges branches in Git?', 'MCQ', 2, 2),
(20, 'What is a remote repository?', 'MCQ', 2, 2),
(20, 'True or False: git push uploads changes to a remote repo.', 'TF', 2, 2),
(20, 'What does git pull do?', 'MCQ', 2, 2),
(20, 'True or False: .gitignore specifies files to exclude.', 'TF', 2, 2),
(21, 'What is Linux?', 'MCQ', 1, 1),
(21, 'True or False: Linux is open-source.', 'TF', 1, 1),
(21, 'Which command lists directory contents?', 'MCQ', 1, 1),
(21, 'What does cd stand for in Linux?', 'MCQ', 1, 1),
(21, 'True or False: Linux is case-sensitive.', 'TF', 1, 1),
(21, 'Which command shows the current directory?', 'MCQ', 1, 1),
(21, 'What is the root user in Linux?', 'MCQ', 2, 2),
(21, 'True or False: chmod changes file permissions.', 'TF', 2, 2),
(21, 'Which directory contains user home folders?', 'MCQ', 2, 2),
(21, 'True or False: Linux uses forward slashes in paths.', 'TF', 1, 1),
(22, 'What is Bash?', 'MCQ', 1, 1),
(22, 'True or False: Bash scripts use .sh extension.', 'TF', 1, 1),
(22, 'Which symbol makes a script executable?', 'MCQ', 2, 2),
(22, 'What does echo command do?', 'MCQ', 1, 1),
(22, 'True or False: Variables in Bash require $ to access.', 'TF', 2, 2),
(22, 'Which operator redirects output to a file?', 'MCQ', 2, 2),
(22, 'What is a loop used for in Bash?', 'MCQ', 2, 2),
(22, 'True or False: Bash supports conditional statements.', 'TF', 2, 2),
(22, 'Which command reads user input in Bash?', 'MCQ', 2, 2),
(22, 'True or False: Bash scripts can call other scripts.', 'TF', 2, 2),
(23, 'What is OOP?', 'MCQ', 1, 1),
(23, 'True or False: Java is object-oriented.', 'TF', 1, 1),
(23, 'What is a class in Java?', 'MCQ', 2, 2),
(23, 'Which keyword creates an object?', 'MCQ', 2, 2),
(23, 'True or False: Inheritance allows code reuse.', 'TF', 2, 2),
(23, 'What is encapsulation in OOP?', 'MCQ', 2, 2),
(23, 'Which access modifier makes members private?', 'MCQ', 2, 2),
(23, 'True or False: Polymorphism means many forms.', 'TF', 2, 2),
(23, 'What is method overriding?', 'MCQ', 3, 3),
(23, 'True or False: Abstract classes cannot be instantiated.', 'TF', 3, 3),
(24, 'What is C++ used for?', 'MCQ', 1, 1),
(24, 'True or False: C++ is a compiled language.', 'TF', 1, 1),
(24, 'Which operator accesses class members?', 'MCQ', 2, 2),
(24, 'What is a pointer in C++?', 'MCQ', 3, 3),
(24, 'True or False: C++ supports operator overloading.', 'TF', 2, 2),
(24, 'What is the purpose of a destructor?', 'MCQ', 3, 3),
(24, 'Which keyword declares a constant?', 'MCQ', 2, 2),
(24, 'True or False: STL stands for Standard Template Library.', 'TF', 2, 2),
(24, 'What is RAII in C++?', 'MCQ', 4, 4),
(24, 'True or False: C++ supports multiple inheritance.', 'TF', 3, 3),
(25, 'What is software testing?', 'MCQ', 1, 1),
(25, 'True or False: Testing finds bugs before release.', 'TF', 1, 1),
(25, 'What is a test case?', 'MCQ', 2, 2),
(25, 'Which testing type verifies individual units?', 'MCQ', 2, 2),
(25, 'True or False: Integration testing checks module interactions.', 'TF', 2, 2),
(25, 'What is regression testing?', 'MCQ', 2, 2),
(25, 'Which testing approach has no predefined test cases?', 'MCQ', 3, 3),
(25, 'True or False: Black box testing requires code knowledge.', 'TF', 2, 2),
(25, 'What is UAT in software testing?', 'MCQ', 2, 2),
(25, 'True or False: Test coverage measures tested code percentage.', 'TF', 2, 2),
(26, 'What is Selenium used for?', 'MCQ', 1, 1),
(26, 'True or False: Selenium automates web browsers.', 'TF', 1, 1),
(26, 'Which language is commonly used with Selenium?', 'MCQ', 2, 2),
(26, 'What is a WebDriver in Selenium?', 'MCQ', 2, 2),
(26, 'True or False: Selenium supports mobile testing.', 'TF', 2, 2),
(26, 'Which method finds elements by ID?', 'MCQ', 2, 2),
(26, 'What is an XPath in Selenium?', 'MCQ', 3, 3),
(26, 'True or False: Selenium Grid enables parallel testing.', 'TF', 3, 3),
(26, 'What does implicit wait do?', 'MCQ', 3, 3),
(26, 'True or False: Page Object Model improves test maintenance.', 'TF', 3, 3),
(27, 'What is Postman used for?', 'MCQ', 1, 1),
(27, 'True or False: Postman tests APIs.', 'TF', 1, 1),
(27, 'Which HTTP method retrieves data?', 'MCQ', 1, 1),
(27, 'What does POST method do?', 'MCQ', 2, 2),
(27, 'True or False: Postman supports automated testing.', 'TF', 2, 2),
(27, 'What is an API endpoint?', 'MCQ', 2, 2),
(27, 'Which status code indicates success?', 'MCQ', 2, 2),
(27, 'True or False: PUT method updates existing resources.', 'TF', 2, 2),
(27, 'What is a collection in Postman?', 'MCQ', 2, 2),
(27, 'True or False: Postman can mock API responses.', 'TF', 3, 3),
(28, 'What is DevOps?', 'MCQ', 1, 1),
(28, 'True or False: DevOps combines development and operations.', 'TF', 1, 1),
(28, 'What is CI/CD?', 'MCQ', 2, 2),
(28, 'Which tool is used for continuous integration?', 'MCQ', 2, 2),
(28, 'True or False: Automation is key to DevOps.', 'TF', 1, 1),
(28, 'What is Infrastructure as Code?', 'MCQ', 3, 3),
(28, 'Which practice monitors application health?', 'MCQ', 2, 2),
(28, 'True or False: DevOps reduces deployment time.', 'TF', 2, 2),
(28, 'What is a pipeline in DevOps?', 'MCQ', 2, 2),
(28, 'True or False: Version control is essential in DevOps.', 'TF', 2, 2),
(29, 'What is Docker?', 'MCQ', 1, 1),
(29, 'True or False: Docker creates containers.', 'TF', 1, 1),
(29, 'What is a Docker image?', 'MCQ', 2, 2),
(29, 'Which command runs a Docker container?', 'MCQ', 2, 2),
(29, 'True or False: Containers share the host OS kernel.', 'TF', 2, 2),
(29, 'What is a Dockerfile?', 'MCQ', 2, 2),
(29, 'Which command builds a Docker image?', 'MCQ', 2, 2),
(29, 'True or False: Docker Hub stores container images.', 'TF', 2, 2),
(29, 'What is Docker Compose used for?', 'MCQ', 3, 3),
(29, 'True or False: Containers are more lightweight than VMs.', 'TF', 2, 2),
(30, 'What is Kubernetes?', 'MCQ', 1, 1),
(30, 'True or False: Kubernetes orchestrates containers.', 'TF', 1, 1),
(30, 'What is a pod in Kubernetes?', 'MCQ', 2, 2),
(30, 'Which component manages cluster state?', 'MCQ', 3, 3),
(30, 'True or False: Kubernetes automates scaling.', 'TF', 2, 2),
(30, 'What is a node in Kubernetes?', 'MCQ', 2, 2),
(30, 'Which object defines desired application state?', 'MCQ', 3, 3),
(30, 'True or False: Services expose pods to network.', 'TF', 2, 2),
(30, 'What is kubectl used for?', 'MCQ', 2, 2),
(30, 'True or False: Kubernetes supports rolling updates.', 'TF', 2, 2),
(31, 'What is AWS?', 'MCQ', 1, 1),
(31, 'True or False: EC2 provides virtual servers.', 'TF', 1, 1),
(31, 'Which AWS service stores objects?', 'MCQ', 1, 1),
(31, 'What is S3 used for?', 'MCQ', 2, 2),
(31, 'True or False: RDS is a managed database service.', 'TF', 2, 2),
(31, 'What does IAM manage in AWS?', 'MCQ', 2, 2),
(31, 'Which service provides serverless computing?', 'MCQ', 2, 2),
(31, 'True or False: VPC creates isolated networks.', 'TF', 2, 2),
(31, 'What is CloudFormation used for?', 'MCQ', 3, 3),
(31, 'True or False: CloudWatch monitors AWS resources.', 'TF', 2, 2),
(32, 'What is Microsoft Azure?', 'MCQ', 1, 1),
(32, 'True or False: Azure is a cloud platform.', 'TF', 1, 1),
(32, 'Which Azure service hosts virtual machines?', 'MCQ', 2, 2),
(32, 'What is Azure Storage used for?', 'MCQ', 2, 2),
(32, 'True or False: Azure supports hybrid cloud.', 'TF', 2, 2),
(32, 'What is Azure App Service?', 'MCQ', 2, 2),
(32, 'Which service provides Azure databases?', 'MCQ', 2, 2),
(32, 'True or False: Azure Active Directory manages identities.', 'TF', 2, 2),
(32, 'What is Azure Functions?', 'MCQ', 2, 2),
(32, 'True or False: Resource groups organize Azure resources.', 'TF', 2, 2),
(33, 'What is Google Cloud Platform?', 'MCQ', 1, 1),
(33, 'True or False: GCP offers cloud computing services.', 'TF', 1, 1),
(33, 'Which service runs virtual machines on GCP?', 'MCQ', 2, 2),
(33, 'What is Cloud Storage in GCP?', 'MCQ', 2, 2),
(33, 'True or False: BigQuery is a data warehouse service.', 'TF', 2, 2),
(33, 'What is Google Kubernetes Engine?', 'MCQ', 2, 2),
(33, 'Which service provides serverless computing?', 'MCQ', 2, 2),
(33, 'True or False: Cloud SQL is a managed database.', 'TF', 2, 2),
(33, 'What is IAM used for in GCP?', 'MCQ', 2, 2),
(33, 'True or False: GCP supports machine learning services.', 'TF', 2, 2),
(34, 'What is Agile methodology?', 'MCQ', 1, 1),
(34, 'True or False: Agile uses iterative development.', 'TF', 1, 1),
(34, 'What is a sprint in Agile?', 'MCQ', 2, 2),
(34, 'Which ceremony reviews sprint progress?', 'MCQ', 2, 2),
(34, 'True or False: Scrum is an Agile framework.', 'TF', 1, 1),
(34, 'What is a product backlog?', 'MCQ', 2, 2),
(34, 'Which role represents stakeholders?', 'MCQ', 2, 2),
(34, 'True or False: Daily standups track team progress.', 'TF', 2, 2),
(34, 'What is velocity in Agile?', 'MCQ', 3, 3),
(34, 'True or False: Agile welcomes changing requirements.', 'TF', 2, 2),
(35, 'What is Power Query?', 'MCQ', 2, 2),
(35, 'True or False: Power Query transforms data.', 'TF', 1, 1),
(35, 'Which tool uses Power Query?', 'MCQ', 2, 2),
(35, 'What does ETL stand for in Power Query?', 'MCQ', 2, 2),
(35, 'True or False: Power Query uses M language.', 'TF', 2, 2),
(35, 'Which step removes duplicate rows?', 'MCQ', 2, 2),
(35, 'What is query folding?', 'MCQ', 3, 3),
(35, 'True or False: Power Query connects to multiple sources.', 'TF', 2, 2),
(35, 'What is a merge operation?', 'MCQ', 2, 2),
(35, 'True or False: Parameters make queries dynamic.', 'TF', 3, 3),
(36, 'What is Tableau used for?', 'MCQ', 1, 1),
(36, 'True or False: Tableau creates data visualizations.', 'TF', 1, 1),
(36, 'Which Tableau product is desktop-based?', 'MCQ', 2, 2),
(36, 'What is a worksheet in Tableau?', 'MCQ', 2, 2),
(36, 'True or False: Dashboards combine multiple views.', 'TF', 2, 2),
(36, 'What is a calculated field?', 'MCQ', 2, 2),
(36, 'Which shelf controls visualization type?', 'MCQ', 2, 2),
(36, 'True or False: Tableau connects to live data sources.', 'TF', 2, 2),
(36, 'What are filters used for?', 'MCQ', 2, 2),
(36, 'True or False: Tableau Server shares dashboards.', 'TF', 2, 2),
(37, 'What is Business Intelligence?', 'MCQ', 1, 1),
(37, 'True or False: BI transforms data into insights.', 'TF', 1, 1),
(37, 'Which process collects data for BI?', 'MCQ', 2, 2),
(37, 'What is a KPI?', 'MCQ', 2, 2),
(37, 'True or False: Dashboards visualize BI metrics.', 'TF', 2, 2),
(37, 'What is data mining in BI?', 'MCQ', 3, 3),
(37, 'Which tool is commonly used for BI reporting?', 'MCQ', 2, 2),
(37, 'True or False: OLAP supports multidimensional analysis.', 'TF', 3, 3),
(37, 'What is a data mart?', 'MCQ', 3, 3),
(37, 'True or False: BI supports data-driven decisions.', 'TF', 1, 1),
(38, 'What is a data warehouse?', 'MCQ', 2, 2),
(38, 'True or False: Data warehouses store historical data.', 'TF', 2, 2),
(38, 'Which schema type uses a star pattern?', 'MCQ', 3, 3),
(38, 'What is a fact table?', 'MCQ', 3, 3),
(38, 'True or False: Dimension tables describe attributes.', 'TF', 2, 2),
(38, 'What is ETL in data warehousing?', 'MCQ', 2, 2),
(38, 'Which process loads data incrementally?', 'MCQ', 3, 3),
(38, 'True or False: Snowflake schema normalizes dimensions.', 'TF', 3, 3),
(38, 'What is a surrogate key?', 'MCQ', 3, 3),
(38, 'True or False: Data warehouses support OLTP.', 'TF', 3, 3),
(39, 'What is Big Data?', 'MCQ', 1, 1),
(39, 'True or False: Hadoop processes large datasets.', 'TF', 1, 1),
(39, 'What are the 3 Vs of Big Data?', 'MCQ', 2, 2),
(39, 'Which component stores data in Hadoop?', 'MCQ', 2, 2),
(39, 'True or False: MapReduce processes data in parallel.', 'TF', 2, 2),
(39, 'What is HDFS?', 'MCQ', 2, 2),
(39, 'Which language queries Hadoop data?', 'MCQ', 3, 3),
(39, 'True or False: Hadoop runs on commodity hardware.', 'TF', 2, 2),
(39, 'What is YARN in Hadoop?', 'MCQ', 3, 3),
(39, 'True or False: Spark is faster than MapReduce.', 'TF', 3, 3),
(40, 'What is cybersecurity?', 'MCQ', 1, 1),
(40, 'True or False: Firewalls protect networks.', 'TF', 1, 1),
(40, 'What is malware?', 'MCQ', 2, 2),
(40, 'Which attack floods servers with traffic?', 'MCQ', 2, 2),
(40, 'True or False: Encryption protects data confidentiality.', 'TF', 2, 2),
(40, 'What is phishing?', 'MCQ', 2, 2),
(40, 'Which principle limits access to necessary resources?', 'MCQ', 3, 3),
(40, 'True or False: VPNs create secure connections.', 'TF', 2, 2),
(40, 'What is two-factor authentication?', 'MCQ', 2, 2),
(40, 'True or False: Patches fix security vulnerabilities.', 'TF', 2, 2),
(41, 'What is ethical hacking?', 'MCQ', 1, 1),
(41, 'True or False: Penetration testing identifies vulnerabilities.', 'TF', 1, 1),
(41, 'What is a white hat hacker?', 'MCQ', 2, 2),
(41, 'Which tool scans for network vulnerabilities?', 'MCQ', 2, 2),
(41, 'True or False: Social engineering exploits human psychology.', 'TF', 2, 2),
(41, 'What is reconnaissance in hacking?', 'MCQ', 2, 2),
(41, 'Which phase involves gaining system access?', 'MCQ', 3, 3),
(41, 'True or False: Metasploit is a penetration testing framework.', 'TF', 2, 2),
(41, 'What is privilege escalation?', 'MCQ', 3, 3),
(41, 'True or False: Ethical hackers require authorization.', 'TF', 1, 1),
(42, 'What is network security?', 'MCQ', 1, 1),
(42, 'True or False: IDS detects intrusions.', 'TF', 2, 2),
(42, 'What protocol secures web traffic?', 'MCQ', 2, 2),
(42, 'Which device filters network traffic?', 'MCQ', 2, 2),
(42, 'True or False: DMZ isolates public-facing servers.', 'TF', 3, 3),
(42, 'What is port scanning?', 'MCQ', 2, 2),
(42, 'Which protocol provides secure remote access?', 'MCQ', 2, 2),
(42, 'True or False: IPS prevents intrusions actively.', 'TF', 3, 3),
(42, 'What is network segmentation?', 'MCQ', 3, 3),
(42, 'True or False: HTTPS uses SSL/TLS encryption.', 'TF', 2, 2),
(43, 'What is cloud security?', 'MCQ', 1, 1),
(43, 'True or False: Shared responsibility model applies to cloud.', 'TF', 2, 2),
(43, 'Which mechanism controls cloud access?', 'MCQ', 2, 2),
(43, 'What is data encryption at rest?', 'MCQ', 2, 2),
(43, 'True or False: Cloud providers handle physical security.', 'TF', 2, 2),
(43, 'What is a security group in cloud?', 'MCQ', 2, 2),
(43, 'Which service protects against DDoS?', 'MCQ', 3, 3),
(43, 'True or False: Multi-tenancy increases security risks.', 'TF', 2, 2),
(43, 'What is cloud access security broker?', 'MCQ', 4, 4),
(43, 'True or False: Compliance is shared in cloud.', 'TF', 3, 3),
(44, 'What is UI design?', 'MCQ', 1, 1),
(44, 'True or False: UX focuses on user experience.', 'TF', 1, 1),
(44, 'What is a wireframe?', 'MCQ', 2, 2),
(44, 'Which principle emphasizes visual hierarchy?', 'MCQ', 2, 2),
(44, 'True or False: Whitespace improves readability.', 'TF', 2, 2),
(44, 'What is user-centered design?', 'MCQ', 2, 2),
(44, 'Which element guides user actions?', 'MCQ', 2, 2),
(44, 'True or False: Consistency improves usability.', 'TF', 2, 2),
(44, 'What are personas in UX design?', 'MCQ', 2, 2),
(44, 'True or False: Accessibility makes designs inclusive.', 'TF', 2, 2),
(45, 'What is Figma?', 'MCQ', 1, 1),
(45, 'True or False: Figma is cloud-based.', 'TF', 1, 1),
(45, 'Which tool creates reusable design elements?', 'MCQ', 2, 2),
(45, 'What is auto layout in Figma?', 'MCQ', 3, 3),
(45, 'True or False: Figma supports real-time collaboration.', 'TF', 1, 1),
(45, 'What are frames in Figma?', 'MCQ', 2, 2),
(45, 'Which feature links design screens?', 'MCQ', 2, 2),
(45, 'True or False: Plugins extend Figma functionality.', 'TF', 2, 2),
(45, 'What is a design system?', 'MCQ', 3, 3),
(45, 'True or False: Figma exports designs as code.', 'TF', 2, 2),
(46, 'What is Adobe XD?', 'MCQ', 1, 1),
(46, 'True or False: Adobe XD creates prototypes.', 'TF', 1, 1),
(46, 'Which feature makes designs interactive?', 'MCQ', 2, 2),
(46, 'What is repeat grid in XD?', 'MCQ', 2, 2),
(46, 'True or False: XD supports voice prototyping.', 'TF', 2, 2),
(46, 'What are artboards in Adobe XD?', 'MCQ', 2, 2),
(46, 'Which mode allows interactive testing?', 'MCQ', 2, 2),
(46, 'True or False: XD integrates with Creative Cloud.', 'TF', 2, 2),
(46, 'What is auto-animate?', 'MCQ', 3, 3),
(46, 'True or False: XD exports design specs for developers.', 'TF', 2, 2),
(47, 'What is Apache Airflow?', 'MCQ', 2, 2),
(47, 'True or False: Airflow orchestrates data workflows.', 'TF', 1, 1),
(47, 'What is a DAG in Airflow?', 'MCQ', 2, 2),
(47, 'Which component executes tasks?', 'MCQ', 3, 3),
(47, 'True or False: Airflow schedules pipeline execution.', 'TF', 2, 2),
(47, 'What is an operator in Airflow?', 'MCQ', 2, 2),
(47, 'Which feature monitors workflow status?', 'MCQ', 2, 2),
(47, 'True or False: Airflow supports Python code.', 'TF', 1, 1),
(47, 'What is task dependency?', 'MCQ', 3, 3),
(47, 'True or False: Airflow handles ETL pipelines.', 'TF', 2, 2),
(48, 'What is data governance?', 'MCQ', 2, 2),
(48, 'True or False: Data governance ensures data quality.', 'TF', 1, 1),
(48, 'Which role oversees data policies?', 'MCQ', 2, 2),
(48, 'What is data lineage?', 'MCQ', 3, 3),
(48, 'True or False: Metadata describes data characteristics.', 'TF', 2, 2),
(48, 'What is master data management?', 'MCQ', 3, 3),
(48, 'Which principle ensures data accuracy?', 'MCQ', 2, 2),
(48, 'True or False: Data catalogs organize data assets.', 'TF', 2, 2),
(48, 'What is data stewardship?', 'MCQ', 2, 2),
(48, 'True or False: Governance includes compliance requirements.', 'TF', 2, 2),
(49, 'What is data storytelling?', 'MCQ', 1, 1),
(49, 'True or False: Storytelling makes data compelling.', 'TF', 1, 1),
(49, 'Which element supports data narratives?', 'MCQ', 2, 2),
(49, 'What is context in storytelling?', 'MCQ', 2, 2),
(49, 'True or False: Visualizations enhance stories.', 'TF', 1, 1),
(49, 'What is the purpose of a data narrative?', 'MCQ', 2, 2),
(49, 'Which technique simplifies complex data?', 'MCQ', 2, 2),
(49, 'True or False: Audience understanding shapes storytelling.', 'TF', 2, 2),
(49, 'What is a call to action in data stories?', 'MCQ', 3, 3),
(49, 'True or False: Stories should have clear conclusions.', 'TF', 2, 2),
(50, 'What is NLP?', 'MCQ', 1, 1),
(50, 'True or False: NLP processes human language.', 'TF', 1, 1),
(50, 'What is tokenization in NLP?', 'MCQ', 2, 2),
(50, 'Which technique removes common words?', 'MCQ', 2, 2),
(50, 'True or False: Sentiment analysis detects emotions.', 'TF', 2, 2),
(50, 'What is named entity recognition?', 'MCQ', 3, 3),
(50, 'Which model processes sequential text?', 'MCQ', 3, 3),
(50, 'True or False: BERT is a transformer model.', 'TF', 3, 3),
(50, 'What is word embedding?', 'MCQ', 3, 3),
(50, 'True or False: NLP enables chatbots.', 'TF', 2, 2),
(51, 'What is computer vision?', 'MCQ', 1, 1),
(51, 'True or False: Computer vision analyzes images.', 'TF', 1, 1),
(51, 'Which task identifies objects in images?', 'MCQ', 2, 2),
(51, 'What is image segmentation?', 'MCQ', 3, 3),
(51, 'True or False: CNNs are used for image processing.', 'TF', 2, 2),
(51, 'What is object detection?', 'MCQ', 2, 2),
(51, 'Which technique extracts image features?', 'MCQ', 3, 3),
(51, 'True or False: OpenCV is a computer vision library.', 'TF', 2, 2),
(51, 'What is facial recognition?', 'MCQ', 2, 2),
(51, 'True or False: Transfer learning reuses trained models.', 'TF', 3, 3),
(52, 'What is prompt engineering?', 'MCQ', 1, 1),
(52, 'True or False: Prompts guide AI model outputs.', 'TF', 1, 1),
(52, 'Which technique provides examples in prompts?', 'MCQ', 2, 2),
(52, 'What is zero-shot prompting?', 'MCQ', 3, 3),
(52, 'True or False: Clear prompts improve AI responses.', 'TF', 1, 1),
(52, 'What is chain-of-thought prompting?', 'MCQ', 3, 3),
(52, 'Which strategy breaks tasks into steps?', 'MCQ', 2, 2),
(52, 'True or False: Context affects prompt effectiveness.', 'TF', 2, 2),
(52, 'What is few-shot learning?', 'MCQ', 3, 3),
(52, 'True or False: Prompt engineering requires iteration.', 'TF', 2, 2);