INSERT INTO course (coursename, coursedescription) VALUES
('Python Programming', 'Learn Python syntax and problem-solving'),
('SQL Fundamentals', 'Write and manage database queries'),
('Data Visualization with Power BI', 'Build interactive data dashboards'),
('Machine Learning Basics', 'Understand key ML algorithms'),
('Deep Learning with TensorFlow', 'Train deep neural networks'),
('Data Analysis with Pandas', 'Clean and analyze data in Python'),
('Statistics for Data Science', 'Grasp core statistical concepts'),
('Data Cleaning and Preparation', 'Fix missing values and errors'),
('Web Development with HTML & CSS', 'Design and style web pages'),
('JavaScript Essentials', 'Add interactivity to web apps'),
('React Framework', 'Build dynamic front-end apps'),
('Backend Development with Node.js', 'Create APIs and servers'),
('Database Design', 'Model scalable database schemas'),
('Advanced SQL Queries', 'Write complex SQL queries'),
('NoSQL with MongoDB', 'Use flexible NoSQL databases'),
('Flask Web Development', 'Create simple web apps'),
('Django Framework', 'Build secure full-stack apps'),
('Git and Version Control', 'Track and manage code versions'),
('Linux Fundamentals', 'Master basic Linux commands'),
('Bash Scripting', 'Automate tasks with shell scripts'),
('Object-Oriented Programming in Java', 'Apply OOP principles'),
('C++ Programming', 'Develop high-performance code'),
('Software Testing Fundamentals', 'Learn testing principles'),
('Automation Testing with Selenium', 'Automate browser tests'),
('API Testing with Postman', 'Test RESTful APIs easily'),
('DevOps Fundamentals', 'Understand CI/CD pipelines'),
('Docker & Containerization', 'Package apps with Docker'),
('Kubernetes Basics', 'Manage containers efficiently'),
('Cloud Computing with AWS', 'Use AWS core cloud services'),
('Azure Fundamentals', 'Explore Azure cloud basics'),
('Google Cloud Platform Basics', 'Start with Google Cloud'),
('Agile Project Management', 'Apply Agile and Scrum'),
('Power Query & ETL', 'Automate data transformation'),
('Tableau Dashboard Design', 'Design data visualizations'),
('Business Intelligence Concepts', 'Understand BI principles'),
('Data Warehousing', 'Implement data storage systems'),
('Big Data with Hadoop', 'Process large data sets'),
('Cybersecurity Fundamentals', 'Protect systems and data'),
('Ethical Hacking', 'Identify system vulnerabilities'),
('Network Security', 'Secure computer networks'),
('Cloud Security', 'Defend cloud environments'),
('UI/UX Design Principles', 'Design user-centered products'),
('Figma for Designers', 'Create UI mockups in Figma'),
('Prototyping with Adobe XD', 'Build interactive designs'),
('Data Engineering with Airflow', 'Automate data workflows'),
('Data Governance', 'Ensure data quality & security'),
('Data Storytelling', 'Communicate insights clearly'),
('Natural Language Processing', 'Work with text data'),
('Computer Vision Basics', 'Analyze image data'),
('Prompt Engineering', 'Write effective AI prompts');
